package papyrus.hotel;

// Code generated by Papyrus Java
// --------------------------------------------------------


/************************************************************/
/**
 * 
 */
public class Room {
	/**
	 * 
	 */
	public int Floor;
	/**
	 * 
	 */
	public int RoomNumber;
	/**
	//public int Qty of beds;
	/**
	 * 
	 */
	public Double Price;

	/**
	 * 
	 */
  public Room() {
		
	}
  
	
	public Room(int floor, int roomNumber, Double price) {
		super();
		Floor = floor;
		RoomNumber = roomNumber;
		Price = price;
	}
	


	public int getFloor() {
		return Floor;
	}


	public void setFloor(int floor) {
		Floor = floor;
	}


	public int getRoomNumber() {
		return RoomNumber;
	}


	public void setRoomNumber(int roomNumber) {
		RoomNumber = roomNumber;
	}


	public Double getPrice() {
		return Price;
	}


	public void setPrice(Double price) {
		Price = price;
	}


	public void CleanRoom() {
	}

	
}
